name: "Ruff GitHub Action"
description: "A GitHub Action of Ruff, an extremely fast Python linter."
author: "The Ruff Community"

inputs:
  args:
    description:
      "Arguments passed to Ruff. Use `ruff --help` to see available options.
      Default: 'check'"
    required: false
    default: "check"

  src:
    description: "Source to run ruff. Default: '.'"
    required: false
    default: "."

  version:
    description: 'The version of ruff to use, e.g. "0.5.0"'
    required: false
    default: ""

  changed-files:
    description: "Whether to only run ruff on changed files. Default: false"
    required: false
    default: "false"

branding:
  color: "black"
  icon: "code"

runs:
  using: composite
  steps:
    - name: Get changed files
      id: changed-files
      if: ${{ inputs.changed-files == 'true' }}
      uses: tj-actions/changed-files@v44
      with:
        files: "**.py"
    - run:
        set +e

        if [ "$RUNNER_OS" == "Windows" ]; then
          runner="python"
        else
          runner="python3"
        fi

        out=$(${runner} $GITHUB_ACTION_PATH/action/main.py)
        exit_code=$?
        echo "${out}"

        exit ${exit_code}
      env:
        RUFF_OUTPUT_FORMAT: github
        INPUT_ARGS: ${{ inputs.args }}
        INPUT_SRC: ${{ inputs.src }}
        INPUT_VERSION: ${{ inputs.version }}
        CHANGED_FILES_ENABLED: ${{ inputs.changed-files }}
        CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        pythonioencoding: utf-8
      shell: bash
